[package]
name = "fides-load"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
fides-proto = { path = "../fides-proto" }

tokio = { workspace = true }
tonic = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
clap = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }

